# ==========================================================
# SECRETS.TOML - FORMATO REFORÇADO (Para garantir a leitura)
# ==========================================================

# ------------------------------------
# [gemini] - CHAVE DA API DO GOOGLE GEMINI
# ------------------------------------
[gemini]
GEMINI_API_KEY = "AIzaSyAlJcSnQ_-xg5f0VIdX5Se5HoKKpwQ11SI" 

# ------------------------------------
# [app] - CONFIGURAÇÕES GERAIS E ADMIN
# ------------------------------------
[app]
DEFAULT_FREE_LIMIT = 3
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com"

# ------------------------------------
# [firebase] - CONFIGURAÇÕES DO FIREBASE ADMIN SDK
# ------------------------------------
[firebase]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"
# CHAVE PRIVADA COMPLETA DO FIREBASE: O Streamlit/Python LEU isso corretamente
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv\\n/6DovQ4BGweremAIE31XJPYkFUVfj+2ptqDHruTSknmRrZAJwg6Fy/xSBTBpM29e\\nn/hkPE_TtKEurwQiHM1ZHcVKUeXwXrpsQeYLx7OR4/uJsIflbJTtQT2qTKH8QQ0n\\nW5mm/shdiyOVLQSZsDTlKOfpdBJITWPioFcl6i4w95B9BhQmOlNvXF05jqaDUkgp\\nOxbO1ACnWRTrUObVjAo/v1bUEnmMOlYV-E1jZvgw7CJiZBfPoSZrKyyh6TScKkZz\\nL0Njonzqopd1jbitgtfJylq582GBCHoZyVxPCSWRGZyUf9RqYicPz7C/+Ri/NsxY\\neL7BQP+LAgMBAAECggEAWKnYQYJEzjU8B58LlB..." 
client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "105650125026907470659"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40assistente-de-marketing-vg.iam.gserviceaccount.com"



