[gemini]
# ----------------------------------------------------------------------
# 1. CHAVE DO GEMINI
# Esta chave DEVE ser a sua chave de API completa e real do Google Gemini.
# ----------------------------------------------------------------------
GEMINI_API_KEY = "AIzaSyAlJcSnQ_-xg5f0VIdX5Se5HoKKpwQ11SI" 

[app]
# ----------------------------------------------------------------------
# 2. CONFIGURAÇÕES GERAIS (As suas informações)
# ----------------------------------------------------------------------
DEFAULT_FREE_LIMIT = 3
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com"

[firebase]
# ----------------------------------------------------------------------
# 3. CHAVES DO FIREBASE (CRÍTICO PARA RESOLVER O ERRO DE MALFORMED FRAMING)
# ----------------------------------------------------------------------
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"
# ----------------------------------------------------------------------
# ATENÇÃO: SUBSTITUA O VALOR ABAIXO PELA SUA CHAVE PRIVADA ESCAPADA.
# Ela deve ser uma ÚNICA string, começando com -----BEGIN PRIVATE KEY-----\\n
# e terminando com \\n-----END PRIVATE KEY-----\\n, sem aspas ou espaços extras
# dentro das aspas (") no início e no fim.
# ----------------------------------------------------------------------
private_key = "O_VALOR_COMPLETO_E_ESCAPADO_DA_SUA_CHAVE_PRIVADA_AQUI"
client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "105650125026907470659"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40assistente-de-marketing-vg.iam.gserviceaccount.com"
