# .streamlit/secrets.toml
# Remova qualquer linha que comece com FIREBASE_ADMIN_CREDENTIAL_JSON

# Chave da OpenAI
OPENAI_API_KEY = "sua_chave_openai_aqui"
DEFAULT_FREE_LIMIT = 3

# Configurações do Firebase Admin SDK - SEÇÃO [firebase]
[firebase]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"

# ⚠️ O campo 'private_key' precisa estar em UMA ÚNICA LINHA,
# com todas as quebras de linha reais substituídas por \\n.
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv\\n... (o restante da sua chave)\\n-----END PRIVATE KEY-----"

client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "108854710987275100925"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"

