# -----------------------------------------------
# 1. CHAVE DE API (CRÍTICO)
# -----------------------------------------------
# Sua chave de API do Gemini/Google AI. 
# O nome da variável DEVE ser 'GEMINI_API_KEY'.
GEMINI_API_KEY = "INSIRA_SUA_CHAVE_DE_API_REAL_AQUI" 

# -----------------------------------------------
# 2. CONFIGURAÇÕES DO APP E ACESSO DEV
# -----------------------------------------------
# Limite de uso gratuito (usado para o plano 'free')
DEFAULT_FREE_LIMIT = 3
# Email do desenvolvedor para acesso PRO ilimitado (whitelist)
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com" 

# -----------------------------------------------
# 3. CONFIGURAÇÃO DO FIREBASE
# -----------------------------------------------
[firebase]
# Copie e cole os valores do seu arquivo JSON de Service Account aqui.
# Certifique-se de que o valor da private_key comece e termine com aspas, 
# e que as quebras de linha sejam substituídas por '\n' (se necessário, o Python já faz a substituição).

type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "SEU_PRIVATE_KEY_ID_AQUI"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "SEU_CLIENT_EMAIL_AQUI"
client_id = "SEU_CLIENT_ID_AQUI"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "SEU_CERT_URL_AQUI"
universe_domain = "googleapis.com"
