Este arquivo contém as variáveis secretas para o Streamlit.
1. CHAVE DO GEMINI (ESSENCIAL PARA A API)
GEMINI_API_KEY = "SUA_CHAVE_DO_GEMINI_AQUI"

2. CONFIGURAÇÕES DO DESENVOLVEDOR E LIMITES
O email do desenvolvedor tem acesso 'premium' forçado.
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com"

Limite de uso para o plano 'free' (3 anúncios gratuitos por sessão)
DEFAULT_FREE_LIMIT = 3

3. CONFIGURAÇÃO DO FIREBASE ADMIN SDK (JSON)
As chaves 'type', 'project_id', 'private_key_id', 'private_key', etc.,
DEVEM ser copiadas EXATAMENTE do arquivo JSON que você me enviou.
[firebase]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"

Cole toda a sua chave privada abaixo, substituindo as quebras de linha '\n'
pelo caracter literal '\n'. Por exemplo:
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv...\n-----END PRIVATE KEY-----\n"
private_key = "COLE AQUI A CHAVE PRIVADA INTEIRA"
client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "104190829399451949163"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40assistente-de-marketing-vg.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
