# CRÍTICO: O nome da variável DEVE ser 'GEMINI_API_KEY'
GEMINI_API_KEY = "" # Deixe vazio até resolver o problema no Streamlit Cloud

[firebase]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"
client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "117281084206588267272"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40assistente-de-marketing-vg.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# IMPORTANTE: A chave privada DEVE ser uma string de múltiplas linhas.
# Copie o conteúdo COMPLETO da sua chave JSON, incluindo as quebras de linha,
# e cole-o aqui, cercado por três aspas triplas.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv
/6DovQ4BGweremAIE31XJPYkFUVfj+2ptqDHruTSknmRrZAJwg6Fy/xSBTBpM29e
n/hkPE+TtKEurwQiHM1ZHcVKUeXwXrpsQeYLx7OR4/uJsIflbJTtQT2qTKH8QQ0n
W5mm/shdiyOVLQSZsDTlKOfpdBJITWPioFcl6i4w95B9BhQmOlNvXF05jqaDUkgp
OxbO1ACnWRTrUObVjAo/v1bUEnmMOlYV+E1jZvgw7CJiZBfPoSZrKyyh6TScKkZz
L0Njonzqopd1jbitgtfJylq582GBCHoZyVxPCSWRGZyUf9RqYicPz7C/+Ri/NsxY
eL7BQP+LAgMBAAECggEAWKnYQYJEzjU8B58LlB...
-----END PRIVATE KEY-----
"""
