# -----------------------------------------------
# 1. CHAVE DE API (CRÍTICO)
# -----------------------------------------------
# Sua chave de API do Gemini/Google AI. 
# O nome da variável DEVE ser 'GEMINI_API_KEY'.
GEMINI_API_KEY = "INSIRA_SUA_CHAVE_DE_API_REAL_AQUI" 

# -----------------------------------------------
# 2. CONFIGURAÇÕES DO APP E ACESSO DEV
# -----------------------------------------------
# Limite de uso gratuito (usado para o plano 'free')
DEFAULT_FREE_LIMIT = 3
# Email do desenvolvedor para acesso PRO ilimitado (whitelist)
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com" 

# -----------------------------------------------
# 3. CONFIGURAÇÃO DO FIREBASE
# -----------------------------------------------
[firebase]
# Credenciais Firebase (baseadas no seu arquivo JSON)
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv\\n/6DovQ4BGweremAIE31XJPYkFUVfj+2ptqDHruTSknmRrZAJwg6Fy/xSBTBpM29e\\nn/hkPE+TtKEurwQiHM1ZHcVKUeXwXrpsQeYLx7OR4/uJsIflbJTtQT2qTKH8QQ0n\\nW5mm/shdiyOVLQSZsDTlKOfpdBJITWPioFcl6i4w95B9BhQmOlNvXF05jqaDUkgp\\nOxbO1ACnWRTrUObVjAo/v1bUEnmMOlYV+E1jZvgw7CJiZBfPoSZrKyyh6TScKkZz\\nL0Njonzqopd1jbitgtfJylq582GBCHoZyVxPCSWRGZyUf9RqYicPz7C/+Ri/NsxY\\neL7BQP+LAgMBAAECggEAWKnYQYJEzjU8B58LlBwza\\nxTADcS8M+WDki7+HAjDyN+aTBrRWnvEoULYp19HJ3gqw4itLhCuHrGvBZpGXKuku\\ndchyvDD/KbvDHuKX66NJfU7743U8ZCtmpxZzG4KneGhq/4zEzQm8UGcjJYoiz68h\\nV/KH43tXL1y99ZVnIjyevN9GZQKBgQDy201UYVDJ18cOBwza\\nxTADcS8M+WDki7+HAjDyN+aTBrRWnvEoULYp19HJ3gqw4itLhCuHrGvBZpGXKuku\\ndchyvDD/KbvDHuKX66NJfU7743U8ZCtmpxZzG4KneGhq/4zEzQm8UGcjJYoiz68h\\nV/KH43tXL1y99ZVnIjyevN9GZQKBgQDGYYtqZtoCBbjm/05ScX8tSeMFYIxGUD8G\\nJcUFbGx8YzBmNj2Z+vXe5PsuCJYdMrzfIjgTMIoLCcIvbH/7YHoXeusOlJRrWnfc\\n8DAfkqa+FqG1RBQv4rYrzDXG8VtRl/AOSW9n8joxpUtVq83HhJP+VTHJYnsuskuA\\nf5OzajAXLwKBgQCKTU2KgikJ6XIYkPdHFwiyzSAoWVROky8taZgKOL98d1L4CWf4\\nt44l4hw8w9B+zy4swUYw64YqC4lZ9zv4E2dlv7p/dXrSMaKFNdI1pcD3PZ+kFr+I\\npBrq...-----END PRIVATE KEY-----\n"
client_email = "SEU_CLIENT_EMAIL_AQUI"
client_id = "SEU_CLIENT_ID_AQUI"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "SEU_CERT_URL_AQUI"
universe_domain = "googleapis.com"
