# Se a sua chave for OpenAI, coloque ela aqui. 
# Se for Gemini/outra que usa este formato, mantenha assim.
# -----------------------------------------------
# 1. CHAVE DE API (CRÍTICO)
# -----------------------------------------------
# Use sua chave de API do Gemini/OpenAI aqui. 
# O nome da variável DEVE ser 'OPENAI_API_KEY'.
OPENAI_API_KEY = "INSIRA_SUA_CHAVE_DE_API_REAL_AQUI" 

# -----------------------------------------------
# 2. CONFIGURAÇÕES DO APP E ACESSO DEV
# -----------------------------------------------
DEFAULT_FREE_LIMIT = 3
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com" 

# -----------------------------------------------
# 3. CONFIGURAÇÃO DO FIREBASE
# -----------------------------------------------
[firebase]
# ... (O restante das suas credenciais do Firebase)

DEFAULT_FREE_LIMIT = 3

# NOVO SEGREDO: E-MAIL DE ACESSO DEV (USO ILIMITADO)
DEVELOPER_EMAIL = "viniciusp.santana07@gmail.com" 

# Configurações do Firebase Admin SDK - SEÇÃO [firebase]
[firebase]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"

# ⚠️ O campo 'private_key' DEVE estar em UMA ÚNICA LINHA, 
# com todas as quebras de linha substituídas por \\n.
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv\\n/6DovQ4BGweremAIE31XJPYkFUVfj+2ptqDHruTSknmRrZAJwg6Fy/xSBTBpM29e\\nn/hkPE+TtKEurwQiHM1ZHcVKUeXwXrpsQeYLx7OR4/uJsIflbJTtQT2qTKH8QQ0n\\nW5mm/shdiyOVLQSZsDTlKOfpdBJITWPioFcl6i4w95B9BhQmOlNvXF05jqaDUkgp\\nOxbO1ACnWRTrUObVjAo/v1bUEnmMOlYV+E1jZvgw7CJiZBfPoSZrKyyh6TScKkZz\\nL0Njonzqopd1jbitgtfJylq582GBCHoZyVxPCSWRGZyUf9RqYicPz7C/+Ri/NsxY\\neL7BQP+LAgMBAAECggEAWKnYQYJEzjU8B58LlBrdqi+t4V/6NlPYTWIghMdws6D/\\ne2GLRghjzcEsfTGkFrTSWr7L1WiUcjvFUHNVdwPjCdejyHa0H84qAL5B4M3M4v3+\nHlq9ovcm5qjeLPR6UeBiGZUPFFieSFXteIlzTnXiuA+BaBqZfD7D7OLkv9vrcRwU\\n/Z2XbzNng6NqHvJNcrW+V+pYdBuEQkT0aZjDIic1gJp7lZHoXPyoOaUui/dtrP2N\\ncThBE43l6wrc1Dh8PWwRc4VcLCY/+c6nFAQ2TA2smd9w8dTJyMFk8z02dGC99TnS\\nKYF1poKSnZYk25PAnkjG8hRakSEXwLa61kNrRwnzIQKBgQDy201UYVDJ18cOBwza\\nxTADcS8M+WDki7+HAjDyN+aTBrRWnvEoULYp19HJ3gqw4itLhCuHrGvBZpGXKuku\\ndchyvDD/KbvDHuKX66NJfU7743U8ZCtmpxZzG4KneGhq/4zEzQm8UGcjJYoiz68h\\nV/KH43tXL1y99ZVnIjyevN9GZQKBgQDGYYtqZtoCBbjm/05ScX8tSeMFYIxGUD8G\\nJcUFbGx8YzBmNj2Z+vXe5PsuCJYdMrzfIjgTMIoLCcIvbH/7YHoXeusOlJRrWnfc\\n8DAfkqa+FqG1RBQv4rYrzDXG8VtRl/AOSW9n8joxpUtVq83HhJP+VTHJYnsuskuA\\nf5OzajAXLwKBgQCKTU2KgikJ6XIYkPdHFwiyzSAoWVROky8taZgKOL98d1L4CWf4\\nt44l4hw8w9B+zy4swUYw64YqC4lZ9zv4E2dlv7p/dXrSMaKFNdI1pcD3PZ+kFr+I\\npBrqzn3ndXCxjnrSEJo8veUeZOB31qI7cORTcr7o9bXxEAxXQW4YUCMu6QKBgQCr\\nJzE/JWllYUZ7lT0fh/oPZ0LqFv+Yn9yT6l5uJv5Qy8tJ3R3P4P7yQn4h9L2b\\n-----END PRIVATE KEY-----"

client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "108854710987275100925"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40assistente-de-marketing-vg.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

