OPENAI_API_KEY = "sua_chave_openai_aqui"
DEFAULT_FREE_LIMIT = 3

[FIREBASE_ADMIN_CREDENTIAL_JSON]
type = "service_account"
project_id = "assistente-de-marketing-vg"
private_key_id = "99ff7b99edd8dfa0306efc9be9e3ea2249478f82"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8Micpk5pi+ySv
/6DovQ4BGweremAIE31XJPYkFUVfj+2ptqDHruTSknmRrZAJwg6Fy/xSBTBpM29e
n/hkPE+TtKEurwQiHM1ZHcVKUeXwXrpsQeYLx7OR4/uJsIflbJTtQT2qTKH8QQ0n
W5mm/shdiyOVLQSZsDTlKOfpdBJITWPioFcl6i4w95B9BhQmOlNvXF05jqaDUkgp
OxbO1ACnWRTrUObVjAo/v1bUEnmMOlYV+E1jZvgw7CJiZBfPoSZrKyyh6TScKkZz
L0Njonzqopd1jbitgtfJylq582GBCHoZyVxPCSWRGZyUf9RqYicPz7C/+Ri/NsxY
eL7BQP+LAgMBAAECggEAWKnYQYJEzjU8B58LlBrdqi+t4V/6NlPYTWIghMdws6D/
e2GLRghjzcEsfTGkFrTSWr7L1WiUcjvFUHNVdwPjCdejyHa0H84qAL5B4M3M4v3+
Hlq9ovcm5qjeLPR6UeBiGZUPFFieSFXteIlzTnXiuA+BaBqZfD7D7OLkv9vrcRwU
/Z2XbzNng6NqHvJNcrW+V+pYdBuEQkT0aZjDIic1gJp7lZHoXPyoOaUui/dtrP2N
cThBE43l6wrc1Dh8PWwRc4VcLCY/+c6nFAQ2TA2smd9w8dTJyMFk8z02dGC99TnS
KYF1poKSnZYk25PAnkjG8hRakSEXwLa61kNrRwnzIQKBgQDy201UYVDJ18cOBwza
xTADcS8M+WDki7+HAjDyN+aTBrRWnvEoULYp19HJ3gqw4itLhCuHrGvBZpGXKuku
ndchyvDD/KbvDHuKX66NJfU7743U8ZCtmpxZzG4KneGhq/4zEzQm8UGcjJYoiz68h
V/KH43tXL1y99ZVnIjyevN9GZQKBgQDGYYtqZtoCBbjm/05ScX8tSeMFYIxGUD8G
JcUFbGx8YzBmNj2Z+vXe5PsuCJYdMrzfIjgTMIoLCcIvbH/7YHoXeusOlJRrWnfc
8DAfkqa+FqG1RBQv4rYrzDXG8VtRl/AOSW9n8joxpUtVq83HhJP+VTHJYnsuskuA
f5OzajAXLwKBgQCKTU2KgikJ6XIYkPdHFwiyzSAoWVROky8taZgKOL98d1L4CWf4
t44l4hw8w9B+zy4swUYw64YqC4lZ9zv4E2dlv7p/dXrSMaKFNdI1pcD3PZ+kFr+I
pBrqzn3ndXCxjnrSEJo8veUeZOB31qI7cORTcr7o9bXxEAxXQW4YUCMu6QKBgQCr
JzE/JWllYUZ7lT0fh+gvTJXe58NeTpFxXlizKy4VywXQyW8wUAKcwXWr66CHpGSr
Jjy24aPXjh3JCJUKbdwoMdZmh+3dCPps1ZTPSJkvWxs85nV8Mt70voSPFWCx7qIf
0V+akLOAbZmnWkh5oHqGbT48/whD63OUc30cx7qh5QKBgFspgjZBeAXOh0FzOWy1
qtT56qAmbj0J1akIYZdsVYoDUBPfBRvNKzKb0lKITaFcDBbi58DTec8SFRCoaUY1
9IuTH9HzfiLbrJnbNVIIx/WuBNp/fVQ2JC6O+FuhagCbybIsa2SdMvZF6aIBSyVL
ia2aFaOjqtQYs8Z8zxHfvz7b
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
client_id = "108854710987275100925"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@assistente-de-marketing-vg.iam.gserviceaccount.com"
